export const TYPOGRAPHY = {
  font100: {
    fontFamily: '"Fira Code", monospace',
    fontSize: '12px',
    fontWeight: 'normal',
    lineHeight: '20px',
  },
  font150: {
    fontFamily: '"Fira Code", monospace',
    fontSize: '12px',
    fontWeight: '500',
    lineHeight: '20px',
  },
  font200: {
    fontFamily: '"Fira Code", monospace',
    fontSize: '14px',
    fontWeight: 'normal',
    lineHeight: '20px',
  },
  font250: {
    fontFamily: '"Fira Code", monospace',
    fontSize: '14px',
    fontWeight: 500,
    lineHeight: '20px',
  },
  font300: {
    fontFamily: '"Fira Code", monospace',
    fontSize: '16px',
    fontWeight: 'normal',
    lineHeight: '24px',
  },
  font350: {
    fontFamily: '"Fira Code", monospace',
    fontSize: '16px',
    fontWeight: 500,
    lineHeight: '24px',
  },
  font400: {
    fontFamily: '"Fira Code", monospace',
    fontSize: '18px',
    fontWeight: 'normal',
    lineHeight: '28px',
  },
  font450: {
    fontFamily: '"Fira Code", monospace',
    fontSize: '18px',
    fontWeight: 500,
    lineHeight: '28px',
  },
  font550: {
    fontFamily: '"Fira Code", monospace',
    fontSize: '20px',
    fontWeight: 500,
    lineHeight: '28px',
  },
  font650: {
    fontFamily: '"Fira Code", monospace',
    fontSize: '24px',
    fontWeight: 500,
    lineHeight: '32px',
  },
  font750: {
    fontFamily: '"Fira Code", monospace',
    fontSize: '28px',
    fontWeight: 500,
    lineHeight: '36px',
  },
  font850: {
    fontFamily: '"Fira Code", monospace',
    fontSize: '32px',
    fontWeight: 500,
    lineHeight: '40px',
  },
  font950: {
    fontFamily: '"Fira Code", monospace',
    fontSize: '36px',
    fontWeight: 500,
    lineHeight: '44px',
  },
  font1050: {
    fontFamily: '"Fira Code", monospace',
    fontSize: '40px',
    fontWeight: 500,
    lineHeight: '52px',
  },
  font1150: {
    fontFamily: '"Fira Code", monospace',
    fontSize: '36px',
    fontWeight: 500,
    lineHeight: '44px',
  },
  font1250: {
    fontFamily: '"Fira Code", monospace',
    fontSize: '44px',
    fontWeight: 500,
    lineHeight: '52px',
  },
  font1350: {
    fontFamily: '"Fira Code", monospace',
    fontSize: '52px',
    fontWeight: 500,
    lineHeight: '64px',
  },
  font1450: {
    fontFamily: '"Fira Code", monospace',
    fontSize: '96px',
    fontWeight: 500,
    lineHeight: '112px',
  },
};
